version: "3.8"
services:
  uptimekuma:
    image: louislam/uptime-kuma:1
    networks:
      - ksp-traefik
    ports:
      - 3001:3001
    volumes:
      - type: bind
        source: /var/swarm-nfs/uptimekuma
        target: /app/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - traefik.enable=true
        - traefik.http.routers.kuma.rule=Host(`kuma.k4czp3r.xyz`)
        - traefik.http.services.kuma.loadbalancer.server.port=3001
        - traefik.http.routers.kuma.tls.certresolver=myresolver
        - traefik.docker.network=ksp-traefik
        - traefik.http.routers.kuma.entrypoints=websecure
        - flame.type=application
        - flame.name=UpTimeKuma
        - flame.url=https://kuma.k4czp3r.xyz
        # - traefik.http.routers.kuma-unsecure.rule=Host(`kuma.k4czp3r.xyz`)
        # - traefik.http.routers.kuma-unsecure.entrypoints=web
        # - traefik.http.routers.kuma-unsecure.middlewares=to-https@file
networks:
  ksp-traefik:
    external: true
